#!/bin/sh
# check process running
#

CMD="nginx"
ARGS="-c /etc/nginx/nginx.conf"

res=0

process=`ps -C $CMD --no-header -o pid,args|grep -e "$ARGS"` || res=1

if [ $res -eq 0 ]; then
    pid=`echo $process |awk '{print $1}'`
    /bin/echo -n "$pid"
fi

exit $res
